### ISSUE TITLE
Filter out games that I commented on

### ISSUE THREAD

**Issue by ttencate** [mkalam-alami/ludumdare-feedback-friends#1]
I would like to be able to enter my username (or user id) so that I don't have to see all the games that I already commented on. Otherwise, I'll keep seeing the same games over and over again and it'll be hard to find something new.

**Comment by mkalam-alami** [comment]
Yep this would be very useful, especially for MiniLDs and very active commenters in general.

I guess the most simple yet performant approach would be to add a new search field with Select2 + a small web service for auto-completion ([relevant SO](http://stackoverflow.com/a/21602199)).

Bonus: Maybe we could put that user selection in the header instead, to make it look like a login form ("view as"?), then remember that info in the session/cookie. OTOH it might not be worth trying too hard: for large events very little users rate more than 10% of the games, so the chances we'd see the same games again and again should be low enough for most people.

**Comment by ttencate** [comment]
But if somebody (especially a large Jam team) is very active with rating, they'll continue to be at the top. It takes just a dozen of such teams to make the entire site less usable. So I think this might be important and am going to start implementing it now, exactly the way you suggest, except not putting it in the header (yet) because the header looks so nice and balanced currently :)

**Comment by ttencate** [comment]
Note that I introduced an extra index (useful even if no username is specified), so you might want to rerun `install.php` for representative performance.

**Comment by mkalam-alami** [comment]
Excellent work! I just updated the sources on the live site.

> But if somebody (especially a large Jam team) is very active with rating, they'll continue to be at the top. It takes just a dozen of such teams to make the entire site less usable. 

True, I didn't think about that. I'm now wondering wondering whether we should tweak the coolness formula to favor the games with few comments over the very active commenters... Issue incoming.
