### ISSUE TITLE
Handle Repeat Comments

### ISSUE THREAD

**Issue by Ajay-Ramachandran** [mkalam-alami/ludumdare-feedback-friends#17]
> Is there a way to check who is commenting in case they repeat? Because my game for miniLD #69 just got 6 comments from the same person and the priority dropped significantly. Also, I feel like replying on your own game page shouldn’t count (it might already not, I’m not too sure).

From Steven Miller (http://ludumdare.com/compo/2016/07/28/introducing-the-feedback-friends-mini-site/#comment-599846/)

**Comment by mkalam-alami** [comment]
This is a bug: while we have set a limit of 3 points per commenter, it doesn't account comments already add in the database during previous runs.

[Part to fix](https://github.com/mkalam-alami/ludumdare-feedback-friends/blob/master/includes/scraping.php#L80) (it should be initialized with the help of a "SELECT SUM(score) FROM comment [...]" query)
