### ISSUE TITLE
Allow cross-origin access to API

### ISSUE THREAD

**Issue by williame** [mkalam-alami/ludumdare-feedback-friends#21]
I am making the LD map use your API, which will ensure that users get a consistent view of their comment status on both UIs.

However, when I try and fetch from api.php I get a COR error:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://feedback.ld.intricati.com/api.php?action=eventsummary&event=undefined. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

The preferred solution is to emit the header.

An alternative solution is to support JSONP, e.g. via an optional callback parameter.

thx

**Comment by williame** [comment]
(I think I can solve this by running my own caching server)

**Comment by mkalam-alami** [comment]
We could certainly open things up with CORS headers or JSONP support, no problem for me.

Now I've been thinking, if we're considering the long term, your map will probably outlive the FF site, so it might not be viable for LD37+ to rely on our API. It's your call though, I don't know how hard it would be to change the code one way or another.

**Comment by mkalam-alami** [comment]
I just added a 'Access-Control-Allow-Origin: *' header. I'm not a CORS expert but I assume it will suffice? Les live website is up to date if you want to try it.

**Comment by williame** [comment]
Works a charm!  Thousand thanks :)
