### ISSUE TITLE
Don't hide the user's own entry in the list

### ISSUE THREAD

**Issue by mkalam-alami** [mkalam-alami/ludumdare-feedback-friends#26]
Showing the user's own entry is useful to see how well it is currently ranking.

Bonus: Maybe there's even a way to highlight it (by using a different cartridge overlay?)

**Comment by ttencate** [comment]
I'll take a look at this one tonight as well if I don't forget.

**Comment by ttencate** [comment]
I couldn't find a way to make a good-looking highlight. I added an `entry-mine` CSS class to the `entry-outer` div, in case you want to have a shot at it.
