### ISSUE TITLE
Fix SQL injection

### ISSUE THREAD

**Issue by ttencate** [mkalam-alami/ludumdare-feedback-friends#3]
Ideally before using this for a live event ;)

I don't know what the usual approach is in PHP, but I hope it doesn't involve mysqli_query and manual escaping everywhere.

**Comment by mkalam-alami** [comment]
Indeed the site needs a security pass, we can do some research to see how query building is best done in PHP+MySQLi. Though for a site this size I wouldn't mind leaving it as it is, as long as things are escaped correctly.

FYI up to now the policy was just:

* Using a restrictive whitelist of allowed characters for $_GET(/$_COOKIE) params, through util_sanitize() ;
* Trust the ludumdare.com pages and just escape their data with mysqli_real_escape_string().

**Comment by ttencate** [comment]
Escaping beats stripping characters ;) I guess the "proper" way would be `mysqli_prepare` and friends. I could take a look some time next week.

Meanwhile I'll add some sanitization at the input level for the stuff I wrote. It doesn't hurt.

**Comment by peachblack** [comment]
Never trust input you don't control. Sanitizing all input is important and using prepared statements correctly will safe your a**.

**Comment by ttencate** [comment]
Thanks to @peachblack this should now be done. If I feel bored, I'll write a nice wrapper to reduce the verbosity and duplication, but the injections are plugged, so I'm closing this.
