### ISSUE TITLE
Fix forcing a rescrape

### ISSUE THREAD

**Issue by hfuller** [mkalam-alami/ludumdare-feedback-friends#32]
When clicking the button on an incorrect entry (e.g., http://feedback.ld.intricati.com/?event=ludum-dare-36&uid=52545) to pull the correct information, the following is returned:

"Cannot write in data/ folder"

**Comment by hfuller** [comment]
Sorry, this may only apply to the production instance, but I don't know how to contact those who are running that instance. I hope this is the correct avenue.

**Comment by hfuller** [comment]
Also, this is no longer urgent as it just got naturally rescraped anyway. :)

**Comment by ttencate** [comment]
Thanks for the report! I'm looking into this. It seems to be a filesystem permissions issue.

**Comment by ttencate** [comment]
A workaround is in place. Your game's image will not be updated until the scrape comes along, however. I opened #33 for that.
