### ISSUE TITLE
Add check for identical comments and/or add report button?

### ISSUE THREAD

**Issue by Biliogadafr** [mkalam-alami/ludumdare-feedback-friends#34]
I see that some people leave the same comment to a lot of games in short amount of time. This is not fair.
For example http://feedback.ld.intricati.com/?event=ludum-dare-36&uid=111717

**Comment by ttencate** [comment]
Blacklisted that user. Leaving this issue open for proper abuse prevention, in case it turns out to be necessary. Please also add any new occurrences here.

**Comment by mkalam-alami** [comment]
@ttencate I left in the Google Drive the SQL query I used for spam detection. It help me detect 2 more spammers.

**Comment by ttencate** [comment]
@mkalam-alami I don't have access to any Google Drive thing. But I wasn't planning to keep chasing down spammers anyway, unless they get reported.

**Comment by mkalam-alami** [comment]
For now we'll keep abuse handling manual: I'll occasionally use MySQL to detect abuse, otherwise we'll just handle cases that people report!
