### ISSUE TITLE
[PSA] Server migration

### ISSUE THREAD

**Issue by mkalam-alami** [mkalam-alami/ludumdare-feedback-friends#45]
A quick message to contributors: the Feedback Friends server has just been migrated, and the DNS now points to my personal VM. The dedicated VM will expire on 2016-10-18, until then you can still access it if there's anything you want to backup.

I'll keep the site up for an undetermined time, but unless the situation evolves so that LD37 needs it, or if there's popular demand I don't think it will be enabled/publicized in the future.

Thanks to all contributors, and @ttencate in particular for making the mini-site much better than initially planned! Hopefully FF will be inspire cool social features for the future Ludum Dare site.

**Comment by ttencate** [comment]
And thank you for getting this ball rolling in the first place, and being so open and welcoming towards contributions! Here's to a fruitful collaboration :beers:
