### ISSUE TITLE
Trophy system(?)

### ISSUE THREAD

**Issue by mkalam-alami** [mkalam-alami/ludumdare-feedback-friends#5]
Leaving the idea here:

> Instead of ratings, I'm considering a stupid but potentially fun trophy system, that will analyze keywords in comments to give awards at the end of the competition, such as "Most WTF Entry", "Cutest Entry", "Least Playable Entry", etc. The awards could then actually be added (manually) on the user entry pages.

**Comment by mkalam-alami** [comment]
Started to study the idea with 5058a3e, and by running some queries against the LD35 DB.

## Can comments predict LD35 winners?

* Most funny entry: Disarranged (actual jam # 2 in humor) (keywords: hilarious,funny,lol)
* Most innovative: Duality (# 4 Innovation) (keywords: original,innov)
* Best mood: A Soul of Clay (# 71 mood) (keywords: mood,atmosphere)
* Best overall: Exhuman (# 424 overall) (keywords: awesome,great,best,loved)

## Various trophy ideas

* Most polished entry: [Black heart](http://ludumdare.com/compo/ludum-dare-35/?action=preview&uid=90316) (polish)
* Most boring entry: [Chorus](http://ldff/index.php?event_id=ludum-dare-35&uid=34259) (boring,annoy,repetitive)
* Most broken entry: [Balthazar The Shapeshifting Wizard](http://ludumdare.com/compo/ludum-dare-35/?action=preview&uid=22612) (not working,broken,cannot play,crashes)
* Most buggy entry: [Dungeophobia](http://ludumdare.com/compo/ludum-dare-35/?action=preview&uid=41895) (buggy,glitch)
* Most WTF entry: [JaJa's Bizarre Transformer](http://ludumdare.com/compo/ludum-dare-35/?action=preview&uid=55414) (wtf,strange)
* Most interesting entry: [Inner Maze](http://ludumdare.com/compo/ludum-dare-35/?action=preview&uid=90795) (interesting)
* Hardest entry: [Exhuman](http://ludumdare.com/compo/ludum-dare-35/?action=preview&uid=84596) (too hard,unfair)

All in all it's a fun way to explore games but there's sometimes not enough samples to choose a winner. Keyword picking is also not always obvious.

**Comment by ttencate** [comment]
Interesting results! Seems to work extraordinarily well for some categories. We don't have ranking data from the scrape, do we? If we did, it wouldn't be too hard to correlate words with ranking automatically for each of the official categories. Trophies aside, it would be an interesting exercise.

I also wonder whether we may have enough data to do automatic clustering of words, to suggest trophies for us :)

**Comment by mkalam-alami** [comment]
Won't do
