### ISSUE TITLE
@-mentions don't pick up my username correctly

### ISSUE THREAD

**Issue by irskep** [mkalam-alami/ludumdare-feedback-friends#54]
When I signed up for ldjam.com, I said my name was "Steve Johnson". It then made my username into `steve-johnson`. But Feedback Friends thinks I'm `Steve Johnson`. People are commenting at me with `@steve-johnson`.

I'm not sure if there's a way to fix this, but if there is, I would appreciate it!

**Comment by mkalam-alami** [comment]
You're right, Feedback Friends should switch from storing the pretty names to actual @-based usernames, as it's what people use for mentions naturally.

I'll try to push an update tonight.

**Comment by mkalam-alami** [comment]
It's now [fixed](http://feedback.ld.intricati.com/?event=9405&uid=16318), thanks for the report :)
