### ISSUE TITLE
LudumDare API Moved api.ldjam.com -> api.ludumdare.com

### ISSUE THREAD

**Issue by zwrawr** [mkalam-alami/ludumdare-feedback-friends#56]
## LudumDare API Moved api.ldjam.com -> api.ludumdare.com
https://twitter.com/mikekasprzak/status/877290908017983488

**Comment by mkalam-alami** [comment]
Thanks for sharing the news! I'll update the sources.

**Comment by mkalam-alami** [comment]
API [moved back](https://twitter.com/mikekasprzak/status/890684126575157248) apparently, I just reversed the change.
