### ISSUE TITLE
Zero results shown for LD39

### ISSUE THREAD

**Issue by irskep** [mkalam-alami/ludumdare-feedback-friends#57]
I realize this might be by design until the jam ends, but I thought I'd open an issue just in case.

**Comment by mkalam-alami** [comment]
Thanks for letting me know, I was just too focused on my own jam entry to check the site haha

I'll fix that tomorrow ;)

**Comment by mkalam-alami** [comment]
I just updated the website to the new API version, game are progressively appearing.

Bad news is, with the big performance issues ldjam.com is currently facing it might take >6h to fetch everything.
