### ISSUE TITLE
Make it easier to skim through games

### ISSUE THREAD

**Issue by mkalam-alami** [mkalam-alami/ludumdare-feedback-friends#7]
Some feedback from the LD announcement:

> vfabien21 says:
> [...]
> But it only allows to efficiently see the top 20 or 50 entries in the category. Could we have page numbers at the bottom to browse a bit deeper ?
> 
> CyberStarLight says:
> [...]
> The only issue is with what vfabien21 said, it loads games really slowly and only shows a few per page.. maybe add another page with less images, stats, etc, that just orders and lists a lot of games with links? when the numbers go higher it’s going to be harder to navigate.
> [...]

The current presentation indeed doesn't let people just "explore" the games, being really focused on just answering "what should I play next".

Possible solutions I could see:

* Load more than 9 games per page
* Make the site full-width to fit in more games
* Make the site automatically load more games once you reach the bottom rather than have the "load more" button 
  * OR Use an old-school pagination system
* Have a more obvious "browse all games" link that would lead to the [LD page](http://ludumdare.com/compo/ludum-dare-35/?action=preview).

**Comment by ttencate** [comment]
Maybe this is what makes it slow (from the docs about [`LIMIT`](http://dev.mysql.com/doc/refman/5.7/en/limit-optimization.html)):

> As soon as MySQL has sent the required number of rows to the client, it aborts the query unless you are using SQL_CALC_FOUND_ROWS. The number of rows can then be retrieved with SELECT FOUND_ROWS().

Indeed I could get the EXPLAIN output to say 9 rows (instead of all the table) if I deleted `SQL_CALC_FOUND_ROWS` _and_ created an index on the thing that's actually being sorted on, namely `(coolness, last_updated)`.

No idea how that will translate into performance, because my database is still too small for sensible measurements and the scrape is being slow.

**Comment by ttencate** [comment]
I pulled the production database down onto my machine and did some profiling. With `SQL_CALC_FOUND_ROWS` it's about 13 ms, without it's about 9 ms, nothing to write home about. But with the index on `(coolness, last_updated)` in place, it's only 0.35 ms, as long as we don't do the slow `SQL_CALC_FOUND_ROWS`.

**Comment by mkalam-alami** [comment]
Hmm we should definitely replace the simple (coolness) index I made with the more complete one.

I guess the SQL_CALC_FOUND_ROWS query also benefits from the index?

**Comment by ttencate** [comment]
No, it doesn't, because to compute that MySQL still has to scan the entire table.

Maybe we can compute it with a simpler, approximate query (e.g. `SELECT COUNT(*) FROM entry WHERE event_id = ...;`), or leave it out altogether.

**Comment by ttencate** [comment]
Meh, actually that optimization stops working as soon as someone enters their username (which I think most people will do). In that case, we have to scan all entries for the event anyway, in order to handle the `HAVING` clause. There's no way to create an index for that because it depends on username.

**Comment by ttencate** [comment]
... and if a username is supplied, the query clocks in at 93 ms on my i7 machine with SSD, slightly slower at 120 ms on the production VPS.

But if we're scanning all the entries anyway, why not just send them all to the client as well? Taking this idea further: why not for each event generate a single, user-independent, deliciously cacheable blob of JSON that lists a summary for each entry in the event, without filtering or sorting applied, and with the uids of all commenters listed?

Then all the rest can be done by JavaScript on the client. We could use a virtual scrolling technique to show all entries on a single page with a sensible scrollbar, and without being slow. All the hard work would be farmed out to the browser, but there's many more of them :)

I did a little test with the following query:

    SELECT entry.uid, entry.author, entry.title, entry.type, entry.platforms, entry.comments_given, entry.comments_received, entry.coolness, entry.last_updated, GROUP_CONCAT(comment.uid_author)
    FROM entry
         LEFT OUTER JOIN comment ON entry.event_id = comment.event_id AND entry.uid = comment.uid_entry
    WHERE entry.event_id = 'ludum-dare-35'
    GROUP BY entry.uid;

The query takes about 130 ms to run, but it would be the only heavy query we need, and its output can easily be cached for 10 seconds or more.

The output (in CSV format) is 544 kB, which gzips to 206 kB.  For comparison: the 9 thumbnails on the front page together are close to 100 kB already. I haven't tried JSON yet; it's probably a bit bigger than CSV but I don't think it will be significant. And browsers [can easily handle](http://josh.zeigler.us/technology/web-development/how-big-is-too-big-for-json/) these amounts of data.

**Comment by ttencate** [comment]
JSON: 227 kB compressed, 849 kB uncompressed.

I just did a hacky prototype. This works. It is fast.

**Comment by ttencate** [comment]
My work in progress is on the `clientside` branch, if you want to try it. Currently, the biggest missing feature is virtual scroll, so it only ever shows the top 9 entries with no way to see more.

**Comment by ttencate** [comment]
Calling it a day. Remaining known issues:

* `{{title}}` (i.e. "These entries need feedback!") does not work.
* Changing options does not change the URL.
* Cartridge on entry page broken.
* Lots of unused code in `page_browse()` now.

But the virtual scroll is done, and works beautifully. It's quite responsive even on my phone (although the list is huuuuuge on there because it all ends up in one column).

**Comment by mkalam-alami** [comment]
It works great, nice job! I've just worked on fixing client-side vs server-side templating btw.

**Comment by ttencate** [comment]
Since it worked for you too, I've merged it into master to avoid merging headache. There is some further cleanup work possible; I'll open new issues for that.

**Comment by mkalam-alami** [comment]
The new search implementation is now live!
