### ISSUE TITLE
Rating system explanation

### ISSUE THREAD

**Issue by zulman** [mkalam-alami/ludumdare-feedback-friends#9]
Hi guys,

Thank you for this awesome LD support project! You're rockstars)

Please help me to understand the core system (link to exact line of code is also fine). So if i have a project and have no comments on other project my rating is 0. Then i commented P of the projects, and my raing is N. 
What the algorithm to get N from P, and how N affects to my project position on the board :) Thank you.

**Comment by mkalam-alami** [comment]
Hi Zulman,

The relevant lines in the code are:

* This, to get how N is computed: https://github.com/mkalam-alami/ludumdare-feedback-friends/blob/master/includes/score.php#L32
* Also, this to understand why we speak of "points" and not directly "comments": https://github.com/mkalam-alami/ludumdare-feedback-friends/blob/master/includes/score.php#L3

If you want to read more about the reasoning behind the rating calculation, you can also check issue #4 (before that I only made a straightforward subtraction).

**Comment by zulman** [comment]
Thank you!
